CREATE TABLE IF NOT EXISTS conteudo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255),
    descricao VARCHAR(1000),
    tipo VARCHAR(20),
    categoria VARCHAR(50),
    url_arquivo VARCHAR(255),
    ultima_atualizacao TIMESTAMP
);

-- EDUCACAO
INSERT INTO conteudo (id, titulo, descricao, tipo, categoria, url_arquivo, ultima_atualizacao)
VALUES (
    1,
    'Alfabetização para adultos',
    'Este conteúdo foi elaborado especialmente para apoiar o processo de alfabetização de jovens e adultos que não tiveram acesso à escola na idade regular. Ele utiliza uma linguagem simples e contextualizada com o cotidiano rural, facilitando a compreensão e o engajamento dos alunos.

O material inclui orientações básicas sobre leitura e escrita, com exercícios práticos e exemplos baseados na realidade do campo. Serve tanto para aprendizado individual quanto para uso em rodas de leitura comunitárias ou atividades mediadas por agentes locais.',
    'TEXTO',
    'EDUCACAO',
    NULL,
    '2025-05-20T08:00:00'
);

-- SAUDE
INSERT INTO conteudo (id, titulo, descricao, tipo, categoria, url_arquivo, ultima_atualizacao)
VALUES (
    2,
    'Prevenção de dengue e doenças tropicais',
    'A cartilha em formato de texto aborda os principais cuidados que devem ser tomados para prevenir doenças como dengue, zika, chikungunya e febre amarela. As informações foram adaptadas à realidade das comunidades rurais, destacando ações simples e eficazes que podem ser implementadas com poucos recursos.

Além disso, o material ensina como reconhecer os sintomas iniciais dessas doenças e quando procurar atendimento médico. O foco está na prevenção através de medidas acessíveis e no fortalecimento da vigilância comunitária em saúde.',
    'TEXTO',
    'SAUDE',
    NULL,
    '2025-05-20T08:10:00'
);

-- CIDADANIA
INSERT INTO conteudo (id, titulo, descricao, tipo, categoria, url_arquivo, ultima_atualizacao)
VALUES (
    3,
    'Como emitir CPF e documentos básicos',
    'Este guia explica, de forma clara e objetiva, os passos necessários para emitir documentos essenciais como CPF, RG e Título de Eleitor, mesmo em localidades onde não há postos fixos de atendimento. O conteúdo aborda também alternativas para quem perdeu seus documentos ou precisa atualizá-los.

São destacadas as parcerias com prefeituras, mutirões e atendimentos itinerantes que frequentemente ocorrem em regiões mais afastadas. O material visa empoderar o cidadão rural a acessar seus direitos básicos de identificação e cidadania.',
    'TEXTO',
    'CIDADANIA',
    NULL,
    '2025-05-20T08:20:00'
);

-- GOVERNO
INSERT INTO conteudo (id, titulo, descricao, tipo, categoria, url_arquivo, ultima_atualizacao)
VALUES (
    4,
    'Agenda do mutirão de serviços públicos',
    'Este conteúdo apresenta um modelo de agenda para divulgação dos mutirões e eventos organizados pelo poder público em comunidades rurais. São incluídas informações sobre datas, horários, locais e os tipos de serviços oferecidos, como emissão de documentos, atendimentos de saúde, vacinação e assistência social.

O objetivo é aproximar os serviços públicos da população que enfrenta barreiras geográficas e de conectividade, permitindo que os moradores planejem sua participação e ampliem o acesso aos direitos fundamentais.',
    'TEXTO',
    'GOVERNO',
    NULL,
    '2025-05-20T08:30:00'
);

-- COMERCIO_LOCAL
INSERT INTO conteudo (id, titulo, descricao, tipo, categoria, url_arquivo, ultima_atualizacao)
VALUES (
    5,
    'Guia de produtores locais',
    'O guia apresenta uma lista de produtores e fornecedores de bens e serviços das próprias comunidades, incentivando o fortalecimento da economia local. Cada entrada contém nome, tipo de produto ou serviço oferecido, e, quando possível, formas de contato direto, como telefone ou ponto de venda fixo.

A proposta é estimular a circulação de renda dentro da própria localidade, criar redes de cooperação e aumentar a visibilidade dos pequenos negócios rurais. Ideal para quem deseja comprar da comunidade e valorizar o trabalho local.',
    'TEXTO',
    'COMERCIO_LOCAL',
    NULL,
    '2025-05-20T08:40:00'
);
